# Generated by Django 3.2.9 on 2023-02-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(blank=True, db_column='Фото', default='images/default2.jpg', null=True, upload_to='images'),
        ),
    ]
